### ISSUE TITLE
Apos pagamento aparece pagina em branco.

### ISSUE THREAD

**Issue by Walber-Sarmento** [danielneis/moodle-enrol_pagseguro#10]
Bom dia Daniel.

Gostaria de uma ajuda sua

Tenho o Moodle 3.1.2+ instalado e o plugin do pagseguro baixado tanto pelo site do Moodle quanto pelo git (Já fiz testes com ambos os plugins) instalado pela ide do Moodle.
já habilitado e configurado com email e Tokem do pagseguro e liberada as inscrições para o curso em questão, Há e também já cadastrei no site do pagseguro o retorno como exemplo abaixo.

http:/meusite/moodle/enrol/pagseguro/process.php

com o parâmetro: transaction_id

Mas na hora de efetuar o pagamento em vez de voltar para o site já com o curso habilitado me retorna uma pagina em branco, ou seja o usuário fez o pagamento mais o curso não é habilitado automaticamente, e recebo um retorno por email com a seguinte frase:

Transaction failed.

Not a valid course id

Sé você pudesse me ajudar ficaria muito agradecido.

fico no aguardo.

**Comment by danielneis** [comment]
cara, vai em Administração do site > Desenvolvimento > Debugging e habilita as mensagens em nível de desenvolvedor e também para mostrar mensagem. Aí cola aqui no github o que aparece que não deve ser mais uma tela em branco.

**Comment by Walber-Sarmento** [comment]
Boa noite

Fiz o que você pediu o resultado foi esse:

Notice: Trying to get property of non-object in /var/www/html/moodle/enrol/pagseguro/process.php on line 56

Pesquisei essa linha ai aparece isso:

$courseid = $plugin_instance->courseid;

To achando que e alguma coisa referente ao ID do curso, pois recebo um e-mail de erro com essa menssagem:

Transaction failed.

Not a valid course id

O:8:"stdClass":41:{s:4:"date";s:29:"2016-09-25T08:54:42.000-03:00";s:4:"code";s:36:"******************************";s:4:"type";s:1:"1";s:6:"status";s:1:"3";s:13:"lasteventdate";s:29:"2016-09-25T09:03:48.000-03:00";s:18:"paymentmethod_type";s:1:"1";s:18:"paymentmethod_code";s:3:"101";s:11:"grossamount";s:4:"1.00";s:14:"discountamount";s:4:"0.00";s:9:"feeamount";s:4:"0.44";s:9:"netamount";s:4:"0.56";s:11:"extraamount";s:4:"0.00";s:13:"escrowenddate";s:29:"2016-10-25T10:03:48.000-02:00";s:16:"installmentcount";s:1:"1";s:9:"itemcount";s:1:"1";s:13:"items_item_id";s:1:"3";s:22:"items_item_description";s:22:"Servidores Windows                                                                               001";s:19:"items_item_quantity";s:1:"1";s:17:"items_item_amount";s:4:"1.00";s:11:"sender_name";s:19:"**************";s:12:"sender_email";s:18:"*********@*********";s:21:"sender_phone_areacode";s:2:"91";s:19:"sender_phone_number";s:9:"******************";s:23:"shipping_address_street";s:19:"********";s:23:"shipping_address_number";s:3:"****";s:27:"shipping_address_complement";O:8:"stdClass":0:{}s:25:"shipping_address_district";s:6:"*************";s:21:"shipping_address_city";s:5:"*********";s:22:"shipping_address_state";s:2:"**";s:24:"shipping_address_country";s:3:"BRA";s:27:"shipping_address_postalcode";s:8:"66075210";s:13:"shipping_type";s:1:"3";s:13:"shipping_cost";s:4:"0.00";s:9:"xmlstring";s:0:"";s:8:"business";s:20:"***********@************";s:14:"receiver_email";s:20:"**********@***********";s:6:"userid";s:2:"23";s:8:"courseid";N;s:10:"instanceid";i:0;s:11:"timeupdated";i:1475013173;s:9:"reference";s:20:"**********@*************";}

**Comment by danielneis** [comment]
Olá, Walber

você conferiu se o plugin foi adicionado ao curso e está habilitado? (Com o "olinho" aberto na página de métodos de inscrição.)

**Comment by Walber-Sarmento** [comment]
Sim, já esta habilitado, mais gostaria de saber qual a versão do php que vc usa para esse plugin pois tá dando alguns erros de LIB também.

**Comment by danielneis** [comment]
olá, você está testando com pagamento via cartão de crédito ou boleto? boleto realmente não está funcionando...

**Comment by danielneis** [comment]
Olá,

como tem outros usuários que conseguiram usar (#11) e também como no moodle.novoaeon.com.br está funcioando (#12), vou fechar essa issue. Caso você venha a utilizar novamente o plugin e tenha dificuldade, peço a gentileza de reabrir.
