### ISSUE TITLE
 Valores individuais para os cursos

### ISSUE THREAD

**Issue by diegoffline** [danielneis/moodle-enrol_pagseguro#11]
como defino valores individuais para os cursos?

**Comment by danielneis** [comment]
olá, você deve ir em cada curso e adicionar o método de inscrição "PagSeguro". Ao adicionar o método de inscrição você poderá informar o valor.

**Comment by diegoffline** [comment]
obrigado Daniel consegui, aqui o problema era o "Theme" que eu estava usando esta muito amarrado, e não me permitiu ver que "método de inscrição" não era apenas uma classe que suportava submenus.


 e era só seguir o caminho: cursos>escolher_o_curso>
                                                            (ai no menu de baixo): >usuarios>métodos de inscrição


nessa parte do métodos de inscrição o tema que eu tinha escolhido já abria o leque de menus ai continha apenas as opções de criação e não de gerar uma nova instância, ai que eu descobri meu erro(coisa de user inexperiente ) que ''métodos de inscrição'' além de uma classe para submenus também poderia ser clicado o tema anterior não era nada indutivo "Roshnilite" o tema é lindo porém de difícil abstração e manutenção.
 Por fim muito obrigado pelo feedback 
o plugin funciona perfeitamente, abraço
