### ISSUE TITLE
Como configurar o pagseguro

### ISSUE THREAD

**Issue by exatabrasil** [danielneis/moodle-enrol_pagseguro#12]
Olá Daniel,
Sou novo no moodle, estou tentando configurar o pagseguro no meu site e não estou conseguindo, será que poderia me ajudar, segue anexo print da tela da minha conta do pagseguro, por favor, diga ai onde esta o erro.
![afoto074](https://cloud.githubusercontent.com/assets/18606448/19623032/ff7a0ab2-9898-11e6-94ca-01d535e494bd.png)

**Comment by exatabrasil** [comment]
A configuração do pagseguro já foi corrigida, o pagamento está sendo aprovado normalmente, entretanto o aluno não está sendo cadastrado automaticamente no curso selecionado. 
![snap](https://cloud.githubusercontent.com/assets/18606448/19648185/0f70911e-99e0-11e6-9393-e27f440ce33d.PNG)

**Comment by danielneis** [comment]
Você está testando via cartão de crédito ou boleto? Por que o boleto realmente não está funcionando ...

**Comment by exatabrasil** [comment]
Via cartão de crédito.

**Comment by danielneis** [comment]
cara, via cartão, eu teste no sandbox e funcionou.
você pode testar no sandbox e confirmar pra mim se também está falhando?

pra isso você vai ter que colocar uma linha como a abaixo no config.php do seu moodle: 

$CFG->pagsegurousesandbox =true;

**Comment by exatabrasil** [comment]
Coloquei a linha, e após isso tentei fazer compra e ocorreu o erro conforme imagem
![afoto083](https://cloud.githubusercontent.com/assets/18606448/19702027/afcb97ce-9adc-11e6-8eaa-1612ed12d231.png)
![afoto084](https://cloud.githubusercontent.com/assets/18606448/19702151/18d5cef6-9add-11e6-877f-02964e8d07b0.png)

**Comment by danielneis** [comment]
ah, sim, agora você tem que configurar sua conta em:

http://sandbox.pagseguro.uol.com.br/

lá tem um menu do lado esquerdo que tem os dados do "vendedor" e do "comprador de teste"

**Comment by exatabrasil** [comment]
Fiz os testes no sandbox mas tambem não cadastrou o aluno ao curso...
Estou usando a verao 3.1 do modle será que é isso?

**Comment by danielneis** [comment]
confirma pra mim que a linha 30 do arquivo moodle/enrol/pagseguro/version.php é igual abaixo:

$plugin->version   = 2016080900;

**Comment by exatabrasil** [comment]
sim, correto.
![afoto085](https://cloud.githubusercontent.com/assets/18606448/19704076/11f3a1a0-9ae5-11e6-97af-34bb2de85579.png)

**Comment by danielneis** [comment]
você colocou um .org no final da sua URL configurada no PagSeguro que não tem no seu wwwroot

**Comment by exatabrasil** [comment]
foi, mas eu já corrigir...

**Comment by danielneis** [comment]
e quando volta pro moodle o que acontece?

podes fazer a gentileza de habilitar o modo de debugging indo em bloco administração > administração do site > desenvolvimento > debugging e marcando a primeira opção como "Desenvolvedor" e também marcar a opção "Mostras mensagens de debugging" ? =)

**Comment by exatabrasil** [comment]
quando volta, aparece a pagina meus cursos, porém sem cadastro do aluno ao curso comprado.
Ok, habilitei o modo debugging como solicitado e agora?

**Comment by danielneis** [comment]
vocÊ está testando com usuário administrador ou um usuário comum?
tem certeza que esse usuário não está inscrito de nenhuma outra forma no mesmo curso ou que não tem alguma mudança de permissão que o impeça de se inscrever?
Qual  versão do MOodle você está utilizando?

(na issue #11 tem uma outra pessoa que configurou com sucesso)

**Comment by exatabrasil** [comment]
Estou usando versao 3.1
Sim, eu excluir todos os usuarios e fiz os testes novamente e nada...
Se puder, acesse o meu moodle www.exataapp9.esy.es e efetue a compra pelo sandbox pagseguro, segue os dados: 
email comprador c92416455441623837441@sandbox.pagseguro.com.br 
Senha: WaHxl67pCpA5knEh
CVV: 123

Já configurei para o pagamento ser aprovado automaticamente.

**Comment by danielneis** [comment]
vc pode me colocar como admin do moodle?

**Comment by exatabrasil** [comment]
sim. ja coloquei

**Comment by danielneis** [comment]
cara, muito estranho, parece tudo configurado certo, realmente.
a mesma coisa funciona em https://moodle.novoaeon.com.br/enrol/index.php?id=33
Comprador: c02847581023226068942@sandbox.pagseguro.com.br
senha: 11389842d5814119
CVV: 123

**Comment by exatabrasil** [comment]
fiz o teste no seu site e deu certo...
Estranho que no meu não dá. 
Vou continuar tentando aqui...

**Comment by danielneis** [comment]
ok, vou fechar a issue aqui. qualquer coisa se encontrar o problema você reabre, ok?

**Comment by exatabrasil** [comment]
ok

**Comment by danielneis** [comment]
cara, só pra ter certeza mesmo, lancei uma nova versão aqui no branch master do github e também lá no https://moodle.org/plugins/enrol_pagseguro

**Comment by exatabrasil** [comment]
vou tentar com a nova versao.

**Comment by raphaelfogaca** [comment]
Olá Daniel, beleza? Pode tentar me ajudar?
Estou tendo o mesmo problema que o amigo acima, realizando os testes no sandbox.
Consigo fazer o pagamento corretamente, retorna para o moodle, mas sem acesso ao curso.
As configurações de autoinscrição do Pagseguro estão ok.

Talvez seja o parametro de retorno que não coloquei corretamente, qual seria o correto?

![erropagseguro](https://cloud.githubusercontent.com/assets/19521294/20440112/bf24bdf0-ada5-11e6-969b-ba54c6f99e73.jpg)

Testei como id, id_pagseguro e transaction_id. Quando eu preencho este campo, retorna o seguinte erro:

"Falta o parâmetro requerido id"

A última versão é essa mesmo? 
>version   = 2016102600;

Obrigado

**Comment by raphaelfogaca** [comment]
Daniel, fazendo alguns testes quando eu ativei o Pagamentos via API e preenchi o parametro do código de transação como transaction_id, o aluno que fez o pagamento retorna para o site com acesso ao curso, muito bom.

Agora estou com outro problema, quando o usuário não está logado no sistema, aparece a mensagem que para ter acesso ao curso é preciso realizar o pagamento, mas o botão que direciona até o PagSeguro não aparece.

Veja: ![inscricaopagseguro](https://cloud.githubusercontent.com/assets/19521294/20440798/a9446a8c-ada8-11e6-8f40-f93991c9db44.jpg)


Pode me dar uma luz? Obrigado

**Comment by danielneis** [comment]
Olá, Raphael

então, cara, nesse caso eu incluí uma mensagem para os usuários que não estão autenticados sobre a necessidade de criar um cadatro ou de se autenticar antes de fazer o pagamento.
Não tem mais muito a fazer, não posso mostrar o botão por que preciso vincular o usuário na hora desse processo.

Espero que seja o suficiente para você, mas se tiver alguma outra sugestão, só mandar.

**Comment by raphaelfogaca** [comment]
Beleza Daniel, pensei nessa possibilidade de remover o acesso de visitantes e deixar somente para autenticados.

Sou iniciante ainda. Queria customizar essa mensagem do custo, é possivel?
Abri todos os arquivos do enrol/pagseguro, mas não encontrei nada.

**Comment by danielneis** [comment]
Olá,

segue o link para o trecho de código que mostra aquele conteúdo:
https://github.com/danielneis/moodle-enrol_pagseguro/blob/master/lib.php#L176-L181

Aí você pode ver as strings que são utilizadas e alterar o que quiser

**Comment by FabianoPretoJr** [comment]
Olá Daniel, 

Estou tentando utilizar o PagSeguro para realizar as inscrições, porém, não aparece em meu Moodle "Métodos de inscrição" na aba usuário. Poderia me ajudar?

**Comment by danielneis** [comment]
Olá, Fabiano
siga atentamente as instruções, a parte da instalação, habilitar o plugin na administração do site, etc. Certifique-se que está usando o Moodle e o plugin nas versões mais recentes.
