### ISSUE TITLE
[[error:generic]] PagSeguro Plataforma Moodle 3.1

### ISSUE THREAD

**Issue by lsolon** [danielneis/moodle-enrol_pagseguro#14]
Daniel 
Bom dia

Primeiramente gostaria de te parabenizar pelo plugin que criou, realmente vejo que seu objetivo foi  facilitar a vida de nós leigos em programação.

Gostaria de te pedir uma grande ajuda, instalei o plugin na minha plataforma onde pretendo disponibilizar cursos diversos, contudo, mesmo seguindo rigorosamente as instruções para implementação do pagseguro no meu site, tenho recebido o [[error:generic]], não sei ao certo onde estou errando.

ja pesquisei ne web e não achei.

conto com sua ajuda.

Grande Abraço.
Leandro Solon.

**Comment by danielneis** [comment]
Acabei de fazer o upload de uma nova versão com uma correção proposta por um colega.
Peço a gentileza de testares novamente e comentar aqui o resultado.

**Comment by lsolon** [comment]
Blz amigo
Boa Noite

o erro agora é outro "Este provedor não é autorizado a usar a API PagSeguro".

Tens ideia do que pode ser?

**Comment by danielneis** [comment]
Isso quer dizer que você não configurou no PagSeguro o endereço correto do seu Moodle.

**Comment by lsolon** [comment]
vou verificar.

ja nem sei mais onde alterei.

mesmo assim valeu.

**Comment by danielneis** [comment]
olá, leandro, conseguiu algum progresso?
Um usuário lá no https://moodle.org/plugins/enrol_pagseguro , comentou que colocando um espaço em branco no final do parâmetro "transaction_id " lá no PagSeguro funcionou pra ele.
Além disso, eu lancei uma versão nova do plugin com uma correçãozinha, não necessariamente ligada com o seu problema, mas vale testar essa nova versão.

grande abraço!

**Comment by danielneis** [comment]
Olá,
um outro usuário encontrou um problema com cursos que tem nomes acima de 100 caracteres.
Eu corrigi esse problema na versão 10. Peço a gentileza de testares com essa nova versão de hoje.

**Comment by danielneis** [comment]
Oi, Leandro

acabei de lançar uma nova versão que deve corrigir o seu problema. Existem casos em que o PagSeguro não retorna um parâmetro que o plugin esperava, agora contornei isso =)

Grande abraço!

**Comment by mikaglemos** [comment]
Boa tarde! Como faço para alterar o layout e local do botão? Exemplo: inserí-lo ao lado das imagens dos cursos.

Abração.

**Comment by danielneis** [comment]
O trecho que imprime o botão está no link abaixo:
https://github.com/danielneis/moodle-enrol_pagseguro/blob/master/lib.php#L173-L202

Fique a vontade para mandar um merge request com suas melhorias =)

Posso fechar essa issue?

Grande abraço!

**Comment by mikaglemos** [comment]
Sim, pode. Obrigada!

Em 13 de fev de 2017 15:00, "Daniel Neis Araujo" <notifications@github.com>
escreveu:
