### ISSUE TITLE
Erro na validação

### ISSUE THREAD

**Issue by casottiAugusto** [danielneis/moodle-enrol_pagseguro#16]
Bom dia não consigo receber do page seguro uma confirmação do pagamento. quando faço a transação ele fica em analise e libera o curso para o cliente fazer ,como posso resolver isso quero que tudo seja automatizado,eu recebo o e-mail falando que o pagamento fi feito com sucesso e o curso foi liberasão.

**Comment by danielneis** [comment]
Olá, você está testando com cartão de crédito ou boleto?

**Comment by casottiAugusto** [comment]
cartão de credito

**Comment by casottiAugusto** [comment]
estou testando com o pagsguro o sandbox

**Comment by danielneis** [comment]
a compra não é confirmada no pagseguro? se for isso, o problema é lá ou na configuração que você efetuou e não no plugin ...
