### ISSUE TITLE
Erro Transaction failed

### ISSUE THREAD

**Issue by guschmitz** [danielneis/moodle-enrol_pagseguro#17]
Boa tarde,

Não estou conseguindo concluir uma compra usando o plugin do pagseguro.
Estou usando o SandBox e efetuando uma compra via cartao de credito. 
Ao concluir a compra eu recebo o seguinte email: 

Transaction failed.

Not a valid user id

O:8:"stdClass":48:{s:4:"date";s:29:"2017-07-21T15:24:32.000-03:00";s:4:"code";s:36:"CF981CA5-8586-4EEB-8B8E-316A90C6CA35";s:4:"type";s:1:"1";s:6:"status";s:1:"3";s:13:"lasteventdate";s:29:"2017-07-21T15:26:03.000-03:00";s:18:"paymentmethod_type";s:1:"1";s:18:"paymentmethod_code";s:3:"101";s:11:"grossamount";s:4:"1.00";s:14:"discountamount";s:4:"0.00";s:9:"feeamount";s:4:"0.44";s:9:"netamount";s:4:"0.56";s:11:"extraamount";s:4:"0.00";s:13:"escrowenddate";s:29:"2017-08-20T15:26:02.000-03:00";s:16:"installmentcount";s:1:"1";s:9:"itemcount";s:1:"1";s:13:"items_item_id";s:1:"3";s:22:"items_item_description";s:22:"Curso
1 - Modulo
unico";s:19:"items_item_quantity";s:1:"1";s:17:"items_item_amount";s:4:"1.00";s:11:"sender_name";s:19:"Comprador
de
Testes";s:12:"sender_email";s:46:"c269@sandbox.pagseguro.com.br";s:21:"sender_phone_areacode";s:2:"11";s:19:"sender_phone_number";s:8:"99999999";s:25:"sender_documents_document";O:8:"stdClass":2:{s:4:"type";s:3:"CPF";s:5:"value";s:11:"";}s:23:"shipping_address_street";s:23:"AVENIDA
DA PEDRA
BRANCA";s:23:"shipping_address_number";s:3:"184";s:27:"shipping_address_complement";O:8:"stdClass":0:{}s:25:"shipping_address_district";s:12:"Pedra
Branca";s:21:"shipping_address_city";s:7:"PALHOCA";s:22:"shipping_address_state";s:2:"SC";s:24:"shipping_address_country";s:3:"BRA";s:27:"shipping_address_postalcode";s:8:"88137270";s:13:"shipping_type";s:1:"3";s:13:"shipping_cost";s:4:"0.00";s:18:"gatewaysystem_type";s:5:"cielo";s:31:"gatewaysystem_authorizationcode";s:1:"0";s:17:"gatewaysystem_nsu";s:1:"0";s:17:"gatewaysystem_tid";s:1:"0";s:31:"gatewaysystem_establishmentcode";s:10:"1056784170";s:26:"gatewaysystem_acquirername";s:5:"CIELO";s:9:"xmlstring";s:2572:"&lt;?xml
version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;
standalone=&quot;yes&quot;?&gt;&lt;transaction&gt;&lt;date&gt;2017-07-21T15:24:32.000-03:00&lt;/date&gt;&lt;code&gt;CF981CA5-8586-4EEB-8B8E-316A90C6CA35&lt;/code&gt;&lt;type&gt;1&lt;/type&gt;&lt;status&gt;3&lt;/status&gt;&lt;lastEventDate&gt;2017-07-21T15:26:03.000-03:00&lt;/lastEventDate&gt;&lt;paymentMethod&gt;&lt;type&gt;1&lt;/type&gt;&lt;code&gt;101&lt;/code&gt;&lt;/paymentMethod&gt;&lt;grossAmount&gt;1.00&lt;/grossAmount&gt;&lt;discountAmount&gt;0.00&lt;/discountAmount&gt;&lt;feeAmount&gt;0.44&lt;/feeAmount&gt;&lt;netAmount&gt;0.56&lt;/netAmount&gt;&lt;extraAmount&gt;0.00&lt;/extraAmount&gt;&lt;escrowEndDate&gt;2017-08-20T15:26:02.000-03:00&lt;/escrowEndDate&gt;&lt;installmentCount&gt;1&lt;/installmentCount&gt;&lt;itemCount&gt;1&lt;/itemCount&gt;&lt;items&gt;&lt;item&gt;&lt;id&gt;3&lt;/id&gt;&lt;description&gt;Curso
1 - Modulo
unico&lt;/description&gt;&lt;quantity&gt;1&lt;/quantity&gt;&lt;amount&gt;1.00&lt;/amount&gt;&lt;/item&gt;&lt;/items&gt;&lt;sender&gt;&lt;name&gt;Comprador
de
Testes&lt;/name&gt;&lt;email&gt;c2@sandbox.pagseguro.com.br&lt;/email&gt;&lt;phone&gt;&lt;areaCode&gt;11&lt;/areaCode&gt;&lt;number&gt;99999999&lt;/number&gt;&lt;/phone&gt;&lt;documents&gt;&lt;document&gt;&lt;type&gt;CPF&lt;/type&gt;&lt;value&gt;&lt;/value&gt;&lt;/document&gt;&lt;/documents&gt;&lt;/sender&gt;&lt;shipping&gt;&lt;address&gt;&lt;street&gt;AVENIDA
DA PEDRA
BRANCA&lt;/street&gt;&lt;number&gt;184&lt;/number&gt;&lt;complement&gt;&lt;/complement&gt;&lt;district&gt;Pedra
Branca&lt;/district&gt;&lt;city&gt;PALHOCA&lt;/city&gt;&lt;state&gt;SC&lt;/state&gt;&lt;country&gt;BRA&lt;/country&gt;&lt;postalCode&gt;88137270&lt;/postalCode&gt;&lt;/address&gt;&lt;type&gt;3&lt;/type&gt;&lt;cost&gt;0.00&lt;/cost&gt;&lt;/shipping&gt;&lt;gatewaySystem&gt;&lt;type&gt;cielo&lt;/type&gt;&lt;rawCode
xsi:nil=&quot;true&quot;
xmlnssi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;/&gt;&lt;rawMessage
xsi:nil=&quot;true&quot;
xmlnssi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;/&gt;&lt;normalizedCode
xsi:nil=&quot;true&quot;
xmlnssi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;/&gt;&lt;normalizedMessage
xsi:nil=&quot;true&quot;
xmlnssi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;/&gt;&lt;authorizationCode&gt;0&lt;/authorizationCode&gt;&lt;nsu&gt;0&lt;/nsu&gt;&lt;tid&gt;0&lt;/tid&gt;&lt;establishmentCode&gt;1056784170&lt;/establishmentCode&gt;&lt;acquirerName&gt;CIELO&lt;/acquirerName&gt;&lt;/gatewaySystem&gt;&lt;/transaction&gt;";s:8:"business";s:19:"meuemail@gmail.com";s:14:"receiver_email";s:19:"meuemail@gmail.com";s:6:"userid";i:0;s:8:"courseid";s:1:"3";s:10:"instanceid";s:1:"8";s:11:"timeupdated";i:1500661572;s:9:"reference";s:19:"meuemail@gmail.com";}

**Comment by danielneis** [comment]
olá,

você está usando a última versão disponível aqui no github? Qual a versão do seu Moodle?
Você utilizou o plugin em um curso que permitia a entrada de visitantes? Se sim, isso não é compatível, você precisa estar autenticado/logado como um usuário que não seja o visitante na hora que volta do PagSeguro.

**Comment by guschmitz** [comment]
Bom dia,

Estou usando a ultima versão do plugin (13).
Meu moodle está na versao 3.1.1.
Aparentemente o problema está no retorno do pagseguro. O moodle nao está identificando o ID de quem fez a compra.
Estou fazendo testes com um navegador logado como ADM e outro como um usuario que está efetuando a compra. Não sei se é esse o problema.

**Comment by danielneis** [comment]
Um dos navegadores está em modo anônimo? Senão não funciona duas sessões de usuários diferentes ...

**Comment by eliasfarah** [comment]
Bom dia Daniel!

Existe alguma forma de desabilitar esse envio de e-mail de erro?

Desde já obrigado!

**Comment by eliasfarah** [comment]
Já encontrei, obrigado!

basta comentar a função pagseguro_message_error_to_admin.

Vlw!
