### ISSUE TITLE
Status do Boleto: aguardando pgto mas aluno foi matriculado

### ISSUE THREAD

**Issue by giselebrugger** [danielneis/moodle-enrol_pagseguro#19]
Olá Daniel, 
Fiz o seguinte teste:
1) realizei um compra de um curso através de **boleto**
2) o boleto esta ainda com status de : **Aguardando Pagamento** 
3) o aluno **foi matriculado automaticamente** no curso **SEM o pagamento** ter sido realizado

olhei alguns logs do apache no horário em que o aluno foi alocado no curso

189.12.170.212 - - [05/Oct/2017:14:01:34 -0300] "GET /moodle/enrol/pagseguro/process.php?transaction_id=74E0EB97-CABF-4909-8774-4BB420D96E78 HTTP/1.1" 303 4142 "https://pagseguro.uol.com.br/checkout/nc/nl/conclusion.jhtml?t=77d8723fa6acb3eb5fc57485172b6746f60ab2c3819ce810" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
189.12.170.212 - - [05/Oct/2017:14:02:40 -0300] "GET /moodle/enrol/pagseguro/return.php?id=3 HTTP/1.1" 303 940 "https://pagseguro.uol.com.br/checkout/nc/nl/conclusion.jhtml?t=77d8723fa6acb3eb5fc57485172b6746f60ab2c3819ce810" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
189.12.170.212 - - [05/Oct/2017:14:02:41 -0300] "GET /moodle/course/view.php?id=3 HTTP/1.1" 200 11628 "https://pagseguro.uol.com.br/checkout/nc/nl/conclusion.jhtml?t=77d8723fa6acb3eb5fc57485172b6746f60ab2c3819ce810" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"

seguem as telas do moodle e pag-seguro
https://qsnapnet.com/snaps/39ouly8dlsv5nrk
https://qsnapnet.com/snaps/ph9aycnlydlpu8f

Nas funcionalidade desta versao (13 - 2017070500) que instalei diz : 
 A inscrição automática via boleto bancário ainda não está funcionando, mas será implementada na próxima versão.
E a versão do moodle : Moodle 3.3.2+ (Build: 20170928)

Vi que vc faz a checagem do status no arquivo:  process.php

define('COMMERCE_PAGSEGURO_STATUS_AWAITING', 1);  ( penso ser este o status de aguardando tanto para boleto quanto para cartão) certo?

aqui se esta aquardando é setado para: pendente

`switch ($data->status) {
        case COMMERCE_PAGSEGURO_STATUS_AWAITING:
        case COMMERCE_PAGSEGURO_STATUS_IN_ANALYSIS:
            $data->payment_status = COMMERCE_PAYMENT_STATUS_PENDING;
            break;
.
.
.
}`
e logo abaixo na linha 220 vc faz o enrol

// Enrol user
    $plugin->enrol_user($plugin_instance, $userid, $plugin_instance->roleid, $timestart, $timeend);

Onde vc faz a verificação do status para efetuar o enrol? não consegui identificar.

Se puder dar uma luz...agradeço demais

**Comment by danielneis** [comment]
Oi, Gisele

a inscrição é feita independente do pagamento do boleto. Na verdade esse é o comportamente que eu queria desde o começo, pois é mais rápido para o usuário acessar o curso. O ideal, claro, que ele fosse desinscrito caso não pague ou mesmo que isso fosse configurável, mas sabe como é.
Atualizei a documentação com a seguinte redação:

"A inscrição automática via boleto bancário é feita quando o boleto é gerado. Não é validada a compensação do boleto, de forma que o usurio deve ser desinscrito manualmente caso no pague o boleto."
