### ISSUE TITLE
Problemas na atualização do plugin PagSeguro

### ISSUE THREAD

**Issue by BrunoRitter292** [danielneis/moodle-enrol_pagseguro#2]
Olá Daniel, 
Fiz a instalação do plugin PagSeguro no meu Moodle e estava recebendo aquele erro de "instanceid" já citado por outros no moodle.org. Vi teus comentários e tentei instalar a versão atualizada que vc disponibilizou aqui. Porém, quando tento instalar essa nova versão, recebo a mensagem de que os arquivos "category", "cohort", "database", flatfile", "guest", "imsenterprise" estão faltando no disco. 
Tentando avançar, recebo a seguinte mensagem de erro: 
O plugin "enrol_imsenterprise" está incorretamente instalado em "$CFG->dirroot/enrol/pagseguro", o local esperado é "$CFG->dirroot/enrol/imsenterprise"

Outras informações sobre este erro

Debug info: 
Error code: detectedmisplacedplugin
Stack trace:
line 463 of /lib/upgradelib.php: plugin_misplaced_exception thrown
line 1647 of /lib/upgradelib.php: call to upgrade_plugins()
line 677 of /admin/index.php: call to upgrade_noncore()

Alguma sugestão?
Obrigado!
Abraço,
Bruno Ritter

**Comment by danielneis** [comment]
Olá, Bruno

você deve instalar o plugin utilizando o git para fazer o download do código, pois pela interface do Moodle dá esses problemas, visto que o plugin que está lá é bem antigo.
Esta nova versão eu peguei de lá e adaptei, mas a que está no site, realmente não funciona instalar num Moodle novo...

**Comment by BrunoRitter292** [comment]
Oi Daniel, 

Obrigado pelo rápido retorno. 

Vc fala fazer o download do caminho
(https://github.com/danielneis/moodle-enrol_pagseguro/archive/update-3.0.zip
[2]) e depois instalar no Moodle como se faz uma instalação de um plugin
qualquer, colocando o arquivo zip? 

Pois foi isso que fiz e não deu certo. 

Ou devo baixar o plugin
(https://moodle.org/plugins/view.php?plugin=enrol_pagseguro [3]) e
depois instalar o update do git? 

Obrigado mais uma vez 

---

 BRUNO RITTER 
Converge Consultoria e Negócios Ltda. 
Telefone: (51) 9107.8991
brunoritter@convergenegocios.com.br
www.convergenegocios.com.br [4]

Em 22.03.2016 13:23, Daniel Neis Araujo escreveu: 

> Olá, Bruno 
> 
> você deve instalar o plugin utilizando o git para fazer o download do código, pois pela interface do Moodle dá esses problemas, visto que o plugin que está lá é bem antigo.
> Esta nova versão eu peguei de lá e adaptei, mas a que está no site, realmente não funciona instalar num Moodle novo... 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub [1]
 

Links:
------
[1]
https://github.com/danielneis/moodle-enrol_pagseguro/issues/2#issuecomment-199889129
[2]
https://github.com/danielneis/moodle-enrol_pagseguro/archive/update-3.0.zip
[3] https://moodle.org/plugins/view.php?plugin=enrol_pagseguro
[4] http://www.convergeengenharia.com.br

**Comment by danielneis** [comment]
Olá, Bruno

veja que se você baixar o zip aqui do github ou fazer o gitclone, o plugin deve ficar no diretorio moodle/enrol/pagseguro
Quando você baixa o zip aqui do github ele vem com outro nome e você tem que corrigir.

**Comment by BrunoRitter292** [comment]
Oi Daniel, 

Deu certo! Consegui atualizar. Porém agora acontece o mesmo problema do
"issue 1" do github. Ao clicar na opção compra pelo pagseguro, aparece
página em branco "....process.php". Já olhei as configurações conforme
vc recomenda no issue 1 e está tudo ok, com "olhinho aberto". 

---

 BRUNO RITTER 
Converge Consultoria e Negócios Ltda. 
Telefone: (51) 9107.8991
brunoritter@convergenegocios.com.br
www.convergenegocios.com.br [2]

Em 22.03.2016 14:32, Daniel Neis Araujo escreveu: 

> Olá, Bruno 
> 
> veja que se você baixar o zip aqui do github ou fazer o gitclone, o plugin deve ficar no diretorio moodle/enrol/pagseguro
> Quando você baixa o zip aqui do github ele vem com outro nome e você tem que corrigir. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub [1]
 

Links:
------
[1]
https://github.com/danielneis/moodle-enrol_pagseguro/issues/2#issuecomment-199923411
[2] http://www.convergeengenharia.com.br
