### ISSUE TITLE
Configuração no Moodle

### ISSUE THREAD

**Issue by andremomb** [danielneis/moodle-enrol_pagseguro#21]
Boa tarde!!!
Fiz a configuração colocando o e-mail e o token da conta de vendedor do Pagseguro. Porém ainda eles consta desabilitado na minha plataforma moodle.

Sabe-se me dizer o motivo?

**Comment by danielneis** [comment]
Olá,

conforme a documentação:
"Com o token criado, volte ao seu Moodle e habilite o plugin indo em "Bloco administração" > Administração do Site > Plugins > Inscrições > Gerenciar plugins de inscrições"

**Comment by andremomb** [comment]
Obrigado pela resposta porém não vejo opção nenhuma para configuração neste caminho.
Pode me dizer qual opção será usado ali? pois o mesmo eu não vejo nada lá realcionado

**Comment by andremomb** [comment]
E o mesmo lá encontra-se desabilitado pra mexer...

**Comment by danielneis** [comment]
então, nesse caminho o plugin deve fazer parte da lista de métodos de autenticação, se não aparece lá é por que teve problema na instalação.
uma vez ele aparecendo lá, você clica no ícone do olho na linha do plugin, isso vai habilitá-lo.
