### ISSUE TITLE
Erro depois do pagamento.

### ISSUE THREAD

**Issue by PedroRHITMO** [danielneis/moodle-enrol_pagseguro#23]
Olá, Daniel.
Parabéns pelo seu sensacional trabalho de desenvolvimento e suporte do plugin pagseguro.

Segue abaixo o erro que ocorre depois que o pagamento foi efetuado no pagseguro e retorna para a moodle.
Os detalhes das versões de todo o projeto também estão abaixo.
Token configurado.
plugin de inscrição ativado e inserido no curso.
**me ajuda?**

Exceção - Argument 1 passed to message_send() must be an instance of core\message\message, instance of stdClass given, called in [dirroot]/enrol/pagseguro/process.php on line 319

Outras informações sobre este erro

Debug info: 
Error code: generalexceptionmessage 

Stack trace: 
line 57 of /lib/messagelib.php: TypeError thrown
line 319 of /enrol/pagseguro/process.php: call to message_send()
line 184 of /enrol/pagseguro/process.php: call to pagseguro_message_error_to_admin()
line 392 of /enrol/pagseguro/process.php: call to pagseguro_handle_transaction()
line 82 of /enrol/pagseguro/process.php: call to pagseguro_handle_redirect_back()

VERSÃO DO PLUGIN:

$plugin->version   = 2019030400;
$plugin->requires  = 2013051401;
$plugin->release   = '14';
$plugin->component = 'enrol_pagseguro';
$plugin->maturity  = MATURITY_STABLE;

Página de redirecionamento fixa
https://rhitmo.com.br/enrol/pagseguro/process.php/

Código de transação para página de redirecionamento
transaction_id 

VERSÂO DA MOODLE
3.6.2+

**Comment by danielneis** [comment]
Olá, Pedro Henrique
acabei de lançar uma nova versão que deve corrigir esse problema.
Obrigado pelo relato do bug com as informações de depuração.
Grande abraço!
