### ISSUE TITLE
Erro versão nova 3.6.2+

### ISSUE THREAD

**Issue by PedroRHITMO** [danielneis/moodle-enrol_pagseguro#24]
![error](https://user-images.githubusercontent.com/49355290/55994424-058dd680-5c88-11e9-9d64-4b30194f1a3e.png)
Olá, Daniel

Segue o erro detectado ao instalar a nova versão no plugin.

Abraço

**Comment by PedroRHITMO** [comment]
Resolvi o erro alterando manualmente '$plugin->requires'

**Comment by PedroRHITMO** [comment]
Novo erro na versão 3.6.2+

![ERROR02](https://user-images.githubusercontent.com/49355290/55995431-d88ef300-5c8a-11e9-8b28-bec8a074126e.png)


Quando o usuário volta do pagseguro tudo ocorre OK

aparece esse erro clico em continuar e o usuário está inscrito no curso...

**Comment by danielneis** [comment]
ok. lancei mais uma versão com correções. agora deve estar ok. :)

**Comment by PedroRHITMO** [comment]
Boa noite, Daniel.
Tudo funcionando.

Obrigado pelo suporte =D
