### ISSUE TITLE
Não aparece opção de PagSeguro

### ISSUE THREAD

**Issue by Phernando82** [danielneis/moodle-enrol_pagseguro#26]
Saudações Daniel! Instalei o plugin do PagSeguro e não aparece como opção para inscrição no curso. Configurei a página de redirecionamento fixa com o caminho .../process.php, código de transação com transaction_id e url de notificação de transação com o caminho .../return.php Configurei o plugin com o email e token do Pagseguro e habilitei auto inscrição para o curso. Na tela principal do moodle, clico no curso e aparece: Você não pode se matricular neste curso. Já procurei varios campos de configuração e não encontro nada que identifique que esteja desabilitado. Poderia me ajudar por favor?

**Comment by danielneis** [comment]
Você deve ir na administração do site e habilitar o método de inscrição PagSeguro.
Depois em cada curso você deve incluir o método de inscrição via PagSeguro e configurar o valor.
Não é através do "auto inscrição".

**Comment by Phernando82** [comment]
Saudações, tem razão. Estava Pagseguro em primeiro na lista de método. Mas no curso somente estava auto inscrição. Esta versão 3.7 não conseguia encontrar onde mudar, precisa ir em administração do site > curso > participantes.

**Comment by Phernando82** [comment]
Muito obrigado.
