### ISSUE TITLE
Erro requireloginerror ao enviar pagamento

### ISSUE THREAD

**Issue by faustocintra** [danielneis/moodle-enrol_pagseguro#27]
Estou tendo o problema abaixo. Alguma luz?

Not enrolled
Error code: requireloginerror
* line 2943 of /lib/moodlelib.php: require_login_exception thrown
* line 498 of /lib/externallib.php: call to require_login()
* line 62 of /admin/tool/usertours/classes/external/tour.php: call to external_api::validate_context()
* line 244 of /lib/externallib.php: call to tool_usertours\external\tour::fetch_and_start_tour()
* line 59 of /lib/ajax/service.php: call to external_api::call_external_function()

**Comment by danielneis** [comment]
Olá, Fausto

parece que o que acontece é que o Moodle está iniciando uma "demonstração de usuário" (user tour) para o usuário que não está autenticado. Você tem configurado alguma demonstração além das padrões do ambiente?

Como o stack trace não mostra nada em relação ao plugin de inscrição, vou fechar essa issue.

**Comment by faustocintra** [comment]
Daniel,

Primeiramente, obrigado pela resposta.

Depois que abri a issue, fui depurar as requisições enviadas pelo Moodle ao PagSeguro e encontrei o motivo do erro.

Acontece que o cliente não gostou de a moeda aparecer como "BRL" para o usuário e exigiu que, nas configurações mostradas na imagem, o valor fosse trocado para "R$".

![2019-07-17_13-31](https://user-images.githubusercontent.com/18018239/61393791-202fa700-a898-11e9-8bb7-9408b04f795b.png)

Depurando as requisições, observei que o valor "BRL" é o esperado pela API do PagSeguro, e tive então um trabalho de convencimento junto ao cliente para que ele aceitasse que, de outra forma, a integração não funcionaria.

Fica, portanto, a sugestão, para as próximas versões do plugin, a implementação de um controle do tipo "select" nas configurações, que possibilitasse a exibição de um nome "legível" para a moeda ao mesmo tempo que enviasse, pelo valor selecionado, a informação esperada pelo PagSeguro.

De resto, meus parabéns e obrigado pelo ótimo trabalho!
