### ISSUE TITLE
Problemas com matrícula no Moodle 3.8

### ISSUE THREAD

**Issue by marcoribeirojr** [danielneis/moodle-enrol_pagseguro#28]
Olá!
Estou usando a versão do Moodle 3.8 e tendo o seguinte problema: quando um pagamento é processado corretamente pelo pagseguro, o estudante recebe um email de confirmação mas a matrícula dele não é realizada pelo plugin.

**Comment by danielneis** [comment]
você pode desabilitar o email de confirmação e ver se funciuna, por favor?

**Comment by danielneis** [comment]
Acabamos de resolver esse problema e lançar uma nova versão aqui no github.
