### ISSUE TITLE
Erro ao adicionar o pagseguro como método de inscrição

### ISSUE THREAD

**Issue by diogokobbi** [danielneis/moodle-enrol_pagseguro#3]
Mensagem exibida: Falta o parâmetro requerido courseid

**Comment by danielneis** [comment]
qual versão do moodle vc está usando?

**Comment by diogokobbi** [comment]
Boa tarde, Daniel. Reinstalei do zero na versão 3.0.3

Retirado do version.php ->
$release  = '3.0.3 (Build: 20160314)'; // Human-friendly version name

**Comment by danielneis** [comment]
preciso que você habilite o modo de depuração do moodle e cole o erro exato com a stack trace

**Comment by diogokobbi** [comment]
Debug info: 
Error code: missingparam

Stack trace: •line 488 of /lib/setuplib.php: moodle_exception thrown
•line 548 of /lib/moodlelib.php: call to print_error()
•line 30 of /enrol/pagseguro/edit.php: call to required_param()

**Comment by danielneis** [comment]
isso é quando vc submete o formulário para adicionar o método de inscrição?

**Comment by diogokobbi** [comment]
Isso mesmo. Procurei testar informando todos os campos e informando só alguns.

**Comment by danielneis** [comment]
e isso acontece quando?

**Comment by diogokobbi** [comment]
Quando eu entro no curso, e vou em usuários > métodos de inscrição > adicionar método.

Ele me redireciona para um formulário. Quando eu preencho os campos e clico em adicionar método ele mostra essa mensagem.

Reparei que a url sempre está com o parâmetro courseid. Mas o action do formulário não está. Não sei se isso pode te ajudar ou se estou falando bobagem.

**Comment by danielneis** [comment]
realmente, o último commit que eu tinha feito tinha quebrado isso.
agora eu arrumei, ao que tudo indica. podes testar com o último commit, por favor?

**Comment by diogokobbi** [comment]
Perfeito! Já permitiu e redirecionou para o pagseguro. Segunda eu faço o teste do pagamento.

Muito obrigado!!!
