### ISSUE TITLE
Integração com pagseguro (moodle 3.2.2 e mensagem persistente de erro)

### ISSUE THREAD

**Issue by anovabr** [danielneis/moodle-enrol_pagseguro#30]
Primeiro, parabéns pelo módulo de integração moodle pagseguro. Estou tomando uma surra na última etapa de integração.
Eu uso o moodle 3.2.2 (nào consigo atualizar) e baixei a versão 2020021000 (17). Fiz a configuração como você orientou: 1) ativei o plugin no moodle e 2) preenchi meu token, mas 3) não preenchi o email.
![image](https://user-images.githubusercontent.com/32950102/78938010-d4f1a000-7a87-11ea-81e0-b57e5a4e2de1.png)

Consigo adicionar o botão no curso.

No pagseguro, configurei a página de redirecionamento fixa, coloquei o transaction_id

![image](https://user-images.githubusercontent.com/32950102/78937805-79bfad80-7a87-11ea-88ef-f2d2e2dc7204.png)

Quando eu acesso o curso para fazer a compra, aparece:
Este provedor não é autorizado a usar a API PagSeguro

Eu já li o seu tutorial, já busquei na internet, já alterei varias vezes o url do site de redirecionamento e nada.

Você poderia me ajudar?
Site: http://ead.anovabr.com/moodle30/?redirect=0
Curso:  http://ead.anovabr.com/moodle30/enrol/index.php?id=7

Me informe se precisa das senhas. Posso te mandar sem problemas.

Muito obrigado

**Comment by danielneis** [comment]
olá. você precisa preencher o email da sua conta do pagseguro no moodle. veja que a opção acima do token está vazia.
