### ISSUE TITLE
Pagamento funciona mas o cadastro não

### ISSUE THREAD

**Issue by henryungaro** [danielneis/moodle-enrol_pagseguro#31]
Olá, estou tendo dificuldades em conseguir realizar o cadastro do usuario, pelos testes que realizei, tanto fora do sandbox como no sandbox, o pagamento é realizado sem problema porem o usuario não é cadastrado no curso.

Segui as recomendações durante a configuração mas o usuario ainda não é incluido

Versão Moodle 3.8.3
Dados da versão do plug-in:
$plugin->version   = 2020042200;
$plugin->requires  = 2018120300;
$plugin->release   = '18';

**Comment by henryungaro** [comment]
Esqueci de mencionar que no ambiente do sandbox, os pagamentos estão "pagos" quando são validados

**Comment by danielneis** [comment]
Olá,
existem duas coisas diferentes no Moodle:
1. O cadastro do usuário na plataforma. Esse cadastro deve ser feito antes de realizar o pagamento.
2. A inscrição do usuário no curso. Após ter feito o cadastro, o usuário vai até o curso que tem o método de inscrição PagSeguro configurado, faz o pagamento e é redirecionado de volta para o curso. Dependendo do método de pagamento, pode ser que a liberação do curso demore alguns segundos/minutos ou até dias (no caso de boleto).
Se alguma coisa nesse processo não funcionou, provavelmente você configurou errado.

**Comment by henryungaro** [comment]
Sobre a configuração de inscrição do usuario no curso, tem mais alguma configuração que precisa configurar ?

**Comment by danielneis** [comment]
Para qual página o usuário é redirecionado após o pagamento no pagseguro?
Se ele volta pra raiz do Moodle provavelmente o problema ta na sua URL de retorno.

**Comment by henryungaro** [comment]
O usuario volta para página inicial do moodle no meu caso, nao sei se a configuração esta errada no pagseguro por parte do site do sandbox ou na configuração dentro do plugin.

**Comment by henryungaro** [comment]
![config plugin](https://user-images.githubusercontent.com/11397053/86304978-e231ad00-bbe6-11ea-8197-bdace9a74c3e.JPG)

No sandbox o pagamento é confirmado

**Comment by henryungaro** [comment]
![image](https://user-images.githubusercontent.com/11397053/86305106-40f72680-bbe7-11ea-8c0b-f1b0bc889d13.png)
Imagem da configuração dentro do curso

**Comment by henryungaro** [comment]
Sera que este problema ocorre porque meu moodle nao é diretamente a pasta raiz ?
Ele está dentro de um site por exemplo, www.meusite.com/moodle/

**Comment by henryungaro** [comment]
![image](https://user-images.githubusercontent.com/11397053/86480265-0ba42300-bd24-11ea-9ffb-faacab41af02.png)
Configuração no ambiente do sandbox
