### ISSUE TITLE
Provedor Não autorizado

### ISSUE THREAD

**Issue by walker007** [danielneis/moodle-enrol_pagseguro#33]
Olá Daniel, tudo bem? Gostaria de parabenizar pela iniciativa de disponibilizar um software open-source.

Estou com um problema na minha aplicação, não consegui identificar o que está acontecendo.

Eu configurei o PagSeguro com a URL da aplicação, URL de Notificação e URL de redirecionamento.
O URL da aplicação eu configurei a URL que os meus alunos entrarão no site, Exemplo: ```https://meusite.com```
As URL's de notificação e redirecionamento firacam algo como: ```https://meusite.com/enrol/pagseguro/process.php```

Porém mesmo com tudo configurado e o SSL da hospedagem ativo e as configurações do PagSeguro, retorna o erro: ```Este provedor não é autorizado a usar a API PagSeguro```

Existe alguma forma de arrumar?

**Comment by micaelomota** [comment]
Olá, acabei de configurar o plugin na versão 3.9 e estou passando pelo mesmo problema.

**Comment by danielneis** [comment]
pessoal, isso é erro de configuração do no pagseguro
