### ISSUE TITLE
Problemas no process.php

### ISSUE THREAD

**Issue by ilorivero** [danielneis/moodle-enrol_pagseguro#4]
Bom dia!

Estou fazendo testes com o plugin do pagseguro, mas verifiquei em outros posts que deveria ser colocado transaction_id nas configurações no site do Pag Seguro, mas parece que no process só aceita o instanceid. Modifiquei isso e parou o erro, mas ele pede o courseid, que não é enviado como retorno pelo Pag Seguro como required_params. 
Outra dúvida: tem como habilitar um sandbox no plugin?
Obrigado!

**Comment by danielneis** [comment]
Olá,

Qual versão do Moodle você está utilizando?
Você está usando a versão mais recente do plugin? Instalou pelo git ou pela interface?

Grande abraço,
Daniel

**Comment by ilorivero** [comment]
Olá, Daniel,

Estou usando a versão 3.0.4. Baixei daqui o plugin. 
MInha dúvida era que em outro post, vi que era para usar transaction_id, mas no arquivo php está instanceid. Daí alterei no PagSeguro para instanceid, mas ele no retorno ele pede courseid também. Fiz algo errado?

[]´s

Ilo

**Comment by danielneis** [comment]
Então, provavelmente você configurou alguma URL ou algum parâmetro errado.
No PagSeguro o valor que você deve informar para "Código de transação para página de redirecionamento" é realmente "transaction_id" sem as aspas.
Se você baixou a última versão aqui do github, deveria funcionar corretamente como para o restante do pessoal.

Grande abraço,
Daniel

**Comment by danielneis** [comment]
Olá, como não obtive mais respostas sobre essa questão e o plugin está funcionando para outras pessoas, vou fechar esta "issue".
