### ISSUE TITLE
Erro no pagseguro

### ISSUE THREAD

**Issue by gilsonajuda** [danielneis/moodle-enrol_pagseguro#5]
Ola bom dia a todos venho tentando solucionar esse problema na integração do modulo do pagseguro  tenho o mesmo funcionando em outra plataforma moodle e esse não esta funcionando me aparece o seguinte erro: "Este provedor não é autorizado a usar a API PagSeguro" estou usando a versão 3.0 tanto do pagseguro como o moodle, tenho uma outra plataforma moodle 2.8 e utilizo a versao antiga do plugin e funciona beleza. Qual a solução para isso? Obrigado

**Comment by danielneis** [comment]
É preciso que no site do PagSeguro você configure corretamente o endereço deste outro servidor que tem outro Moodle para que ele possa usar a API do PagSeguro.
Não tenho certeza se é possível para uma mesma conta do PagSeguro usar a API em mais que um site com endereços diferentes, mas talvez seja.
