### ISSUE TITLE
Alunos não são cadastrados automaticamente

### ISSUE THREAD

**Issue by amandarlc** [danielneis/moodle-enrol_pagseguro#6]
Prezados,

Meu moodle é na versão 2.7 e baixei uma versão anterior do plugin do PagSeguro (sem ser a 3.0). Aparece a página para o aluno se cadastrar e pagar via pagseguro. Um aluno fez um pagamento no valor de 1 real para testar, o pagamento foi aprovado no Pag, eu recebi email de confirmação do Pag, mas o acesso ao curso ainda não foi liberado para o aluno. Poderia me ajudar com esse problema? Obrigada!

**Comment by danielneis** [comment]
Oi, Amanda

eu pediria a gentileza de atualizares para a versão mais recente do plugin para eu poder te ajudar.
Se você atualizar e o erro persistir, aí continuamos aqui, ok?

Grande abraço,
Daniel

**Comment by amandarlc** [comment]
Oi, Daniel! Eu já tentei atualizar para a versão mais recente do plugin e não consigo. Eu teria que atualizar o Moodle para a versão 3.0, nesse caso?

**Comment by danielneis** [comment]
Depende, para fazer pela interface web, sim.
Se voce baixar pelo git, poderá usar na versao 2.9, embora tenha que fazer uma pequena alteraçao no arquivo version.php do plugin. Eu coloquei no site só as versoes que eu testei, entao se voce testar e funcionar eu troco lá no site para dar suporte ao 2.9 também.

**Comment by amandarlc** [comment]
Eu baixei a nova versão pelo git e fiz apenas a alteração no version.php para ficar compatível, mas continuo com o mesmo problema de antes: aparece a opção de pagar pelo pagseguro, eu pago como aluna, volto para a página do curso, mas o acesso não está liberado e continua apenas aparecendo a tela com a opção de fazer o pagamento. Imagino que, nesse caso, terei de atualizar o próprio moodle.

**Comment by danielneis** [comment]
Olá, Amanda

qual forma de pagamento voce utilizou no PagSeguro?
Você teria como olhar se no Moodle ficou registrado algum log referente à inscrição?
Se sim, poderias colar o log aqui?

**Comment by amandarlc** [comment]
Daniel, atualizei o moodle para a versão 3.0.3 e baixei a versão mais recente do plugin do Pagseguro aqui pelo github. Habilitei o pagamento pelo Pagseguro, com o olhinho aberto e tudo mais. Criei uma conta de estudante e aparece a opção de fazer o pagamento do curso pelo Pag e eu consigo fazer e receber o pagamento, mas:

1) o curso não é liberado automaticamente para o aluno
2) configurei o código de transação para "transacion_id" (sem aspas) e a página de redirecionamento fixa do meu site para enrol/pagseguro/return.php (com a URL do site antes, claro), mas após o pagamento, aparece no meu moodle a mensagem "Falta o parâmetro requerido id" e, como disse, o curso continua bloqueado para o aluno. 

Fiz algo errado ou ainda tem algo que precisa ser feito?

**Comment by danielneis** [comment]
Oi, Amanda

acabei de lançar uma nova versão aqui no Github e também lá no Moodle.org que corrige a inscrição automática.
Podes fazer a gentileza baixar a nova versão (você vai ter que desinstalar a versão antiga e instalar a nova para funcioanr corretamente, pois não implementei o update) e testar para nós?

Grande abraço,
Daniel

**Comment by danielneis** [comment]
Oi, Amanda

você teve algum progresso nisso?

Você está testando com pagamento via cartão de crédito ou boleto? boleto realmente não está funcionando...

**Comment by amandarlc** [comment]
Olá, Daniel,

Não funcionou nem via boleto, nem cartão. Simplesmente não redirecionava,
nem desbloqueava o curso para o aluno. Tínhamos que fazer tudo manualmente.
Tentamos de tudo. No fim das contas, desistimos do plugin, porque
precisávamos para um curso que ministramos em agosto.



Em 25 de outubro de 2016 17:22, Daniel Neis Araujo <notifications@github.com

**Comment by danielneis** [comment]
Olá,

como tem outros usuários que conseguiram usar (#11) e também como no moodle.novoaeon.com.br está funcioando (#12), vou fechar essa issue. Caso vocÊs venham a utilizar novamente o plugin e tenham dificuldade novamente, peço a gentileza de reabrir.
