### ISSUE TITLE
tenho mais de um curso na plataforma

### ISSUE THREAD

**Issue by diegoffline** [danielneis/moodle-enrol_pagseguro#7]
Olá Bom dia, 
tenho mais de um curso na minha plataforma,
 é possivel cada curso ter um preço diferente ?
att Diego Marchetti.

**Comment by danielneis** [comment]
Olá, Diego 

A idéia é justamente essa. Você pode adicionar uma instância do plugin em cada curso e cobrar um valor diferente.

Grande abraço,
Daniel
