### ISSUE TITLE
Após devolução do dinheiro no site do Pagseguro o aluno continua inscrito no curso

### ISSUE THREAD

**Issue by lucasmmendes** [danielneis/moodle-enrol_pagseguro#9]
Não há desinscrição automatica no curso após devolução do dinheiro no site do pagseguro.

Recebo o seguinte e-mail do Moodle de erro após devolver o dinheiro (substitui os dados pessoais por "*".

---

Assunto: 
pagseguro ERROR: Not a valid user id

Corpo:

Prev Odonto Sistema de Ensino®:  Transaction failed.

Not a valid user id

O:8:"stdClass":41:{s:4:"date";s:29:"2016-09-18T14:41:16.000-03:00";s:4:"code";s:36:"CAAD2A10-2223-434D-BDEB-2D60C267D004";s:4:"type";s:1:"1";s:6:"status";s:1:"6";s:13:"lasteventdate";s:29:"2016-09-18T14:49:17.000-03:00";s:18:"paymentmethod_type";s:1:"1";s:18:"paymentmethod_code";s:3:"102";s:11:"grossamount";s:4:"1.00";s:14:"discountamount";s:4:"0.00";s:9:"feeamount";s:4:"0.44";s:9:"netamount";s:4:"0.56";s:11:"extraamount";s:4:"0.00";s:13:"escrowenddate";s:29:"2016-10-18T15:44:55.000-02:00";s:16:"installmentcount";s:1:"1";s:9:"itemcount";s:1:"1";s:13:"items_item_id";s:2:"20";s:22:"items_item_description";s:7:"EndNote";s:19:"items_item_quantity";s:1:"1";s:17:"items_item_amount";s:4:"1.00";s:11:"sender_name";s:14:"***********_";s:12:"sender_email";s:23:"**_********_@gmail.com";s:21:"sender_phone_areacode";s:2:"14";s:19:"sender_phone_number";s:9:"**_********_";s:23:"shipping_address_street";s:16:"**_********_";s:23:"shipping_address_number";s:4:"1380";s:27:"shipping_address_complement";s:5:"AP
21";s:25:"shipping_address_district";s:9:"Pinheiros";s:21:"shipping_address_city";s:9:"SAO
PAULO";s:22:"shipping_address_state";s:2:"SP";s:24:"shipping_address_country";s:3:"BRA";s:27:"shipping_address_postalcode";s:8:"**_********_";s:13:"shipping_type";s:1:"3";s:13:"shipping_cost";s:4:"0.00";s:9:"xmlstring";s:1675:"&lt;?xml
version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;
standalone=&quot;yes&quot;?&gt;&lt;transaction&gt;&lt;date&gt;2016-09-18T14:41:16.000-03:00&lt;/date&gt;&lt;code&gt;CAAD2A10-2223-434D-BDEB-2D60C267D004&lt;/code&gt;&lt;type&gt;1&lt;/type&gt;&lt;status&gt;6&lt;/status&gt;&lt;lastEventDate&gt;2016-09-18T14:49:17.000-03:00&lt;/lastEventDate&gt;&lt;paymentMethod&gt;&lt;type&gt;1&lt;/type&gt;&lt;code&gt;102&lt;/code&gt;&lt;/paymentMethod&gt;&lt;grossAmount&gt;1.00&lt;/grossAmount&gt;&lt;discountAmount&gt;0.00&lt;/discountAmount&gt;&lt;feeAmount&gt;0.44&lt;/feeAmount&gt;&lt;netAmount&gt;0.56&lt;/netAmount&gt;&lt;extraAmount&gt;0.00&lt;/extraAmount&gt;&lt;escrowEndDate&gt;2016-10-18T15:44:55.000-02:00&lt;/escrowEndDate&gt;&lt;installmentCount&gt;1&lt;/installmentCount&gt;&lt;itemCount&gt;1&lt;/itemCount&gt;&lt;items&gt;&lt;item&gt;&lt;id&gt;20&lt;/id&gt;&lt;description&gt;EndNote&lt;/description&gt;&lt;quantity&gt;1&lt;/quantity&gt;&lt;amount&gt;1.00&lt;/amount&gt;&lt;/item&gt;&lt;/items&gt;&lt;sender&gt;&lt;name&gt;**_********_&lt;/name&gt;&lt;email&gt;**_********_@gmail.com&lt;/email&gt;&lt;phone&gt;&lt;areaCode&gt;14&lt;/areaCode&gt;&lt;number&gt;**_********_&lt;/number&gt;&lt;/phone&gt;&lt;/sender&gt;&lt;shipping&gt;&lt;address&gt;&lt;street&gt;**_********_&lt;/street&gt;&lt;number&gt;1380&lt;/number&gt;&lt;complement&gt;**_********_&lt;/complement&gt;&lt;district&gt;Pinheiros&lt;/district&gt;&lt;city&gt;SAO
PAULO&lt;/city&gt;&lt;state&gt;SP&lt;/state&gt;&lt;country&gt;BRA&lt;/country&gt;&lt;postalCode&gt;05409010&lt;/postalCode&gt;&lt;/address&gt;&lt;type&gt;3&lt;/type&gt;&lt;cost&gt;0.00&lt;/cost&gt;&lt;/shipping&gt;&lt;/transaction&gt;";s:8:"business";s:30:"**_********_@**_********_.com.br";s:14:"receiver_email";s:30:"**_********_@**_********_.com.br";s:6:"userid";N;s:8:"courseid";N;s:10:"instanceid";N;s:11:"timeupdated";i:1474220959;s:9:"reference";s:30:"**_********_@**_*********.com.br";}

**Comment by danielneis** [comment]
Sim, esta funcionalidade não estava prevista.
Se você é desenvolvedor, eu ficaria muito feliz em receber um pull request com essa funcionalidade.
Caso não possas desenvovler e queiras patrocinar o desenvolvimento desta funcionalidade, por favor me mande um email =)

**Comment by danielneis** [comment]
Na nova versão lançada agora mesmo, caso o dinheiro seja devolvido, o usuário terá sua inscrição suspensa automaticamente.
